#!/bin/bash
# ── Deploy Crowdfunding Platform to Stellar Testnet ────────────────────────────
# This script:
#   1. Builds the contract
#   2. Creates & funds a deployer identity
#   3. Deploys a SAC token contract (FUND)
#   4. Deploys the crowdfunding contract
#   5. Initializes the contract
#   6. Outputs contract IDs to .env

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
FRONTEND_DIR="$PROJECT_DIR/frontend"

NETWORK="testnet"
IDENTITY="crowdfund-deployer"

echo "══════════════════════════════════════════════════════"
echo "  Stellar Crowdfunding Platform — Testnet Deployment"
echo "══════════════════════════════════════════════════════"
echo ""

cd "$PROJECT_DIR"

# ── Step 1: Build ─────────────────────────────────────────────────────────────

echo "▸ Step 1/6: Building contract..."
bash "$SCRIPT_DIR/build.sh"
echo ""

WASM_PATH="target/wasm32-unknown-unknown/release/soroban_crowdfunding_contract.wasm"

# ── Step 2: Identity ──────────────────────────────────────────────────────────

echo "▸ Step 2/6: Setting up deployer identity..."

if ! stellar keys show "$IDENTITY" 2>/dev/null; then
  stellar keys generate "$IDENTITY" --network "$NETWORK"
  echo "  ✓ Generated new identity: $IDENTITY"
else
  echo "  ✓ Using existing identity: $IDENTITY"
fi

DEPLOYER_ADDRESS=$(stellar keys address "$IDENTITY")
echo "  Address: $DEPLOYER_ADDRESS"

# Fund via Friendbot
echo "  Funding via Friendbot..."
curl -s "https://friendbot.stellar.org?addr=$DEPLOYER_ADDRESS" > /dev/null 2>&1 || true
echo "  ✓ Funded on testnet"
echo ""

# ── Step 3: Deploy SAC Token ─────────────────────────────────────────────────

echo "▸ Step 3/6: Deploying SAC token (FUND)..."

TOKEN_CONTRACT_ID=$(stellar contract asset deploy \
  --asset "FUND:$DEPLOYER_ADDRESS" \
  --source "$IDENTITY" \
  --network "$NETWORK" 2>&1 | tail -1)

echo "  ✓ Token Contract ID: $TOKEN_CONTRACT_ID"
echo ""

# ── Step 4: Deploy Crowdfunding Contract ─────────────────────────────────────

echo "▸ Step 4/6: Deploying crowdfunding contract..."

CROWDFUNDING_CONTRACT_ID=$(stellar contract deploy \
  --wasm "$WASM_PATH" \
  --source "$IDENTITY" \
  --network "$NETWORK" 2>&1 | tail -1)

echo "  ✓ Crowdfunding Contract ID: $CROWDFUNDING_CONTRACT_ID"
echo ""

# ── Step 5: Initialize Platform ──────────────────────────────────────────────

echo "▸ Step 5/6: Initializing platform contract..."

stellar contract invoke \
  --id "$CROWDFUNDING_CONTRACT_ID" \
  --source "$IDENTITY" \
  --network "$NETWORK" \
  -- initialize \
  --admin "$DEPLOYER_ADDRESS" \
  --token_id "$TOKEN_CONTRACT_ID"

echo "  ✓ Platform initialized"
echo ""

# ── Step 6: Write .env ───────────────────────────────────────────────────────

echo "▸ Step 6/6: Writing configuration..."

ENV_FILE="$FRONTEND_DIR/.env"
cat > "$ENV_FILE" << EOF
# Stellar Crowdfunding — Generated by deploy.sh
# $(date)

VITE_CROWDFUNDING_CONTRACT_ID=$CROWDFUNDING_CONTRACT_ID
VITE_TOKEN_CONTRACT_ID=$TOKEN_CONTRACT_ID
VITE_NETWORK_PASSPHRASE=Test SDF Network ; September 2015
VITE_RPC_URL=https://soroban-testnet.stellar.org
EOF

echo "  ✓ Wrote $ENV_FILE"
echo ""

# ── Done ─────────────────────────────────────────────────────────────────────

echo "══════════════════════════════════════════════════════"
echo "  ✅ Deployment Complete!"
echo "══════════════════════════════════════════════════════"
echo ""
echo "  Crowdfund Contract: $CROWDFUNDING_CONTRACT_ID"
echo "  Token Contract:     $TOKEN_CONTRACT_ID"
echo "  Deployer:           $DEPLOYER_ADDRESS"
echo ""
echo "  Next steps:"
echo "    cd frontend"
echo "    npm run dev"
echo ""
